
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec 11 2025 04:29:26 IST (Dec 10 2025 22:59:26 UTC)

// Verification Directory fv/elevator_controller 

module elevator_controller(clk, rst_n, in_car_req, hall_up_req,
     hall_down_req, floor_sensor, door_open_sensor, door_closed_sensor,
     overload, emergency_stop, maintenance_mode, door_open_btn,
     door_close_btn, motor_up, motor_down, door_open_cmd,
     door_close_cmd, motor_brake, current_floor, pending_debug);
  input clk, rst_n, door_open_sensor, door_closed_sensor, overload,
       emergency_stop, maintenance_mode, door_open_btn, door_close_btn;
  input [7:0] in_car_req, hall_up_req, hall_down_req, floor_sensor;
  output motor_up, motor_down, door_open_cmd, door_close_cmd,
       motor_brake;
  output [2:0] current_floor;
  output [7:0] pending_debug;
  wire clk, rst_n, door_open_sensor, door_closed_sensor, overload,
       emergency_stop, maintenance_mode, door_open_btn, door_close_btn;
  wire [7:0] in_car_req, hall_up_req, hall_down_req, floor_sensor;
  wire motor_up, motor_down, door_open_cmd, door_close_cmd, motor_brake;
  wire [2:0] current_floor;
  wire [7:0] pending_debug;
  wire [2:0] target_floor;
  wire [2:0] state;
  wire [7:0] door_timer;
  wire dir_up, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_16, n_19, n_20, n_21, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_37, n_38, n_39, n_40, n_41, n_43, n_44, n_45;
  wire n_46, n_48, n_49, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_200, n_201;
  NAND2XL g10706__2398(.A (n_148), .B (n_158), .Y (n_160));
  SDFFRHQX1 \target_floor_reg[1] (.RN (rst_n), .CK (clk), .D (n_156),
       .SI (target_floor[1]), .SE (n_159), .Q (target_floor[1]));
  SDFFRHQX1 \target_floor_reg[0] (.RN (rst_n), .CK (clk), .D (n_157),
       .SI (target_floor[0]), .SE (n_159), .Q (target_floor[0]));
  SDFFRHQX1 \target_floor_reg[2] (.RN (rst_n), .CK (clk), .D (n_154),
       .SI (target_floor[2]), .SE (n_159), .Q (target_floor[2]));
  AOI221XL g10709__5107(.A0 (state[0]), .A1 (n_142), .B0 (n_140), .B1
       (n_124), .C0 (n_152), .Y (n_158));
  OAI21XL g10718__6260(.A0 (n_57), .A1 (n_155), .B0 (n_151), .Y
       (n_157));
  OAI22X1 g10716__4319(.A0 (n_153), .A1 (n_145), .B0 (n_83), .B1
       (n_155), .Y (n_156));
  OAI32X1 g10719__8428(.A0 (n_153), .A1 (n_150), .A2 (n_141), .B0
       (n_98), .B1 (n_155), .Y (n_154));
  NOR2XL g10715__5526(.A (emergency_stop), .B (n_147), .Y (n_152));
  DFFSHQX1 dir_up_reg(.SN (rst_n), .CK (clk), .D (n_146), .Q (dir_up));
  NAND4BXL g10720__6783(.AN (n_150), .B (n_134), .C (n_144), .D
       (n_127), .Y (n_151));
  NAND3X1 g10713__3680(.A (n_143), .B (n_119), .C (n_148), .Y (n_149));
  AOI211XL g10717__1617(.A0 (n_52), .A1 (n_38), .B0 (maintenance_mode),
       .C0 (n_131), .Y (n_147));
  OAI21XL g10712__2802(.A0 (n_128), .A1 (n_159), .B0 (n_139), .Y
       (n_146));
  NAND4XL g10721__1705(.A (n_114), .B (n_122), .C (n_144), .D (n_135),
       .Y (n_145));
  AOI21XL g10722__5122(.A0 (state[1]), .A1 (n_142), .B0 (n_132), .Y
       (n_143));
  OAI22X1 g10728__8246(.A0 (n_138), .A1 (n_140), .B0 (n_116), .B1
       (n_136), .Y (n_141));
  OAI31X1 g10714__7098(.A0 (n_133), .A1 (n_137), .A2 (n_159), .B0
       (dir_up), .Y (n_139));
  OAI32X1 g10731__6131(.A0 (n_138), .A1 (n_111), .A2 (n_137), .B0
       (n_94), .B1 (n_136), .Y (n_150));
  AOI32X1 g10730__1881(.A0 (n_134), .A1 (n_120), .A2 (n_129), .B0
       (n_113), .B1 (n_133), .Y (n_135));
  NOR2XL g10723__5115(.A (n_130), .B (n_140), .Y (n_132));
  NOR2XL g10725__7482(.A (n_130), .B (n_155), .Y (n_131));
  NAND4XL g10736__4733(.A (n_134), .B (n_121), .C (n_117), .D (n_129),
       .Y (n_144));
  NOR2XL g10732__6161(.A (n_126), .B (n_129), .Y (n_140));
  AOI21XL g10734__9315(.A0 (n_133), .A1 (n_125), .B0 (n_153), .Y
       (n_128));
  NAND2XL g10733__9945(.A (n_133), .B (n_129), .Y (n_155));
  MXI2XL g10729__2883(.A (n_115), .B (n_118), .S0 (n_126), .Y (n_127));
  CLKINVX1 g10740(.A (n_129), .Y (n_137));
  NOR2XL g10738__2346(.A (n_123), .B (n_125), .Y (n_153));
  INVXL g10724(.A (n_159), .Y (n_124));
  NOR2BX1 g10743__1666(.AN (n_123), .B (n_125), .Y (n_129));
  OAI211XL g10735__7410(.A0 (n_121), .A1 (n_120), .B0 (n_134), .C0
       (n_126), .Y (n_122));
  NAND2BX1 g10726__6417(.AN (n_130), .B (n_119), .Y (n_159));
  AND2XL g10741__5477(.A (n_117), .B (n_112), .Y (n_118));
  DFFRHQX1 \door_timer_reg[5] (.RN (rst_n), .CK (clk), .D (n_108), .Q
       (door_timer[5]));
  NAND3BX1 g10751__2398(.AN (n_136), .B (n_82), .C (n_116), .Y (n_125));
  OAI22X1 g10748__5107(.A0 (n_109), .A1 (n_110), .B0 (n_97), .B1
       (n_96), .Y (n_115));
  DFFRHQX1 \door_timer_reg[4] (.RN (rst_n), .CK (clk), .D (n_106), .Q
       (door_timer[4]));
  NAND2XL g10752__6260(.A (dir_up), .B (n_113), .Y (n_114));
  OAI211X1 g10727__4319(.A0 (n_71), .A1 (n_103), .B0 (n_23), .C0
       (n_14), .Y (n_130));
  NAND2BXL g10744__8428(.AN (n_121), .B (n_111), .Y (n_112));
  NAND2BX1 g10756__5526(.AN (n_110), .B (n_109), .Y (n_136));
  INVXL g10747(.A (n_107), .Y (n_108));
  NOR2XL g10745__6783(.A (dir_up), .B (n_133), .Y (n_126));
  AOI21X1 g10764__3680(.A0 (n_102), .A1 (n_109), .B0 (n_100), .Y
       (n_113));
  AOI32X1 g10749__1617(.A0 (door_timer[3]), .A1 (door_timer[4]), .A2
       (n_101), .B0 (door_timer[5]), .B1 (n_105), .Y (n_107));
  AO22XL g10750__2802(.A0 (door_timer[4]), .A1 (n_105), .B0
       (door_timer[3]), .B1 (n_74), .Y (n_106));
  OAI21X1 g10755__1705(.A0 (n_85), .A1 (n_104), .B0 (n_92), .Y (n_111));
  NOR3X1 g10757__5122(.A (n_87), .B (n_104), .C (n_138), .Y (n_133));
  OR4XL g10742__8246(.A (n_73), .B (n_72), .C (n_66), .D (n_200), .Y
       (n_103));
  NAND2XL g10761__7098(.A (n_102), .B (n_99), .Y (n_110));
  NAND2XL g10759__6131(.A (n_117), .B (n_104), .Y (n_120));
  SDFFRHQX1 \door_timer_reg[3] (.RN (rst_n), .CK (clk), .D (n_101), .SI
       (n_88), .SE (door_timer[3]), .Q (door_timer[3]));
  INVXL g10767(.A (n_99), .Y (n_100));
  OAI211X1 g10765__1881(.A0 (target_floor[2]), .A1 (n_98), .B0 (n_32),
       .C0 (n_84), .Y (n_148));
  OAI21X1 g10760__5115(.A0 (door_timer[3]), .A1 (n_90), .B0 (n_89), .Y
       (n_105));
  NOR2BX1 g10769__7482(.AN (n_97), .B (n_96), .Y (n_99));
  NAND3BX1 g10766__6161(.AN (n_121), .B (n_134), .C (n_117), .Y
       (n_138));
  NAND2XL g10768__9315(.A (n_116), .B (n_81), .Y (n_94));
  OAI21X1 g10776__9945(.A0 (n_76), .A1 (n_93), .B0 (n_92), .Y (n_104));
  DFFRHQX1 \state_reg[2] (.RN (rst_n), .CK (clk), .D (n_79), .Q
       (state[2]));
  OAI32X1 g10763__2883(.A0 (door_timer[2]), .A1 (n_60), .A2 (n_90), .B0
       (n_53), .B1 (n_77), .Y (n_91));
  CLKINVX1 g10772(.A (n_88), .Y (n_89));
  OAI21X1 g10773__2346(.A0 (n_67), .A1 (n_86), .B0 (n_85), .Y (n_87));
  AOI211X1 g10788__1666(.A0 (target_floor[1]), .A1 (n_83), .B0 (n_33),
       .C0 (n_58), .Y (n_84));
  INVXL g10786(.A (n_81), .Y (n_82));
  NOR2XL g10789__7410(.A (floor_sensor[7]), .B (n_80), .Y (n_96));
  DFFRHQX1 \pending_reg[0] (.RN (rst_n), .CK (clk), .D (n_69), .Q
       (pending_debug[0]));
  NAND2XL g10758__6417(.A (n_119), .B (n_61), .Y (n_79));
  NAND2XL g10790__5477(.A (current_floor[2]), .B (n_75), .Y (n_92));
  OAI21X1 g10775__2398(.A0 (door_timer[2]), .A1 (n_90), .B0 (n_77), .Y
       (n_88));
  NAND2XL g10793__5107(.A (n_76), .B (n_75), .Y (n_116));
  DFFRHQX1 \pending_reg[7] (.RN (rst_n), .CK (clk), .D (n_68), .Q
       (pending_debug[7]));
  DFFRHQX1 \pending_reg[3] (.RN (rst_n), .CK (clk), .D (n_75), .Q
       (pending_debug[3]));
  NOR2XL g10791__6260(.A (n_54), .B (n_93), .Y (n_81));
  DFFRHQX1 \door_timer_reg[1] (.RN (rst_n), .CK (clk), .D (n_64), .Q
       (door_timer[1]));
  NOR2BX1 g10777__4319(.AN (n_101), .B (door_timer[4]), .Y (n_74));
  DFFRHQX1 \pending_reg[6] (.RN (rst_n), .CK (clk), .D (n_73), .Q
       (pending_debug[6]));
  NAND2XL g10782__8428(.A (n_65), .B (n_72), .Y (n_102));
  DFFRHQX1 \pending_reg[4] (.RN (rst_n), .CK (clk), .D (n_71), .Q
       (pending_debug[4]));
  DFFRHQX1 \pending_reg[2] (.RN (rst_n), .CK (clk), .D (n_56), .Q
       (pending_debug[2]));
  SDFFRHQX1 \door_timer_reg[0] (.RN (rst_n), .CK (clk), .D (n_63), .SI
       (n_62), .SE (door_timer[0]), .Q (door_timer[0]));
  NAND2XL g10794__5526(.A (n_98), .B (n_71), .Y (n_109));
  INVXL g10803(.A (n_86), .Y (n_69));
  CLKINVX1 g10804(.A (n_68), .Y (n_80));
  NAND2XL g10800__6783(.A (n_67), .B (n_66), .Y (n_123));
  NAND2BX1 g10796__3680(.AN (n_59), .B (n_73), .Y (n_97));
  NOR2BX1 g10795__1617(.AN (n_71), .B (n_65), .Y (n_121));
  NAND2XL g10802__2802(.A (floor_sensor[7]), .B (n_73), .Y (n_134));
  AO22XL g10787__1705(.A0 (n_5), .A1 (n_63), .B0 (door_timer[1]), .B1
       (n_62), .Y (n_64));
  AOI32X1 g10774__5122(.A0 (state[1]), .A1 (n_26), .A2 (n_27), .B0
       (state[2]), .B1 (n_142), .Y (n_61));
  AOI21X1 g10792__8246(.A0 (n_60), .A1 (n_63), .B0 (n_62), .Y (n_77));
  DFFRHQX1 \pending_reg[5] (.RN (rst_n), .CK (clk), .D (n_72), .Q
       (pending_debug[5]));
  NAND2XL g10785__7098(.A (n_59), .B (n_72), .Y (n_117));
  OAI211X1 g10807__6131(.A0 (target_floor[0]), .A1 (n_57), .B0 (n_41),
       .C0 (n_46), .Y (n_58));
  AOI21X1 g10809__1881(.A0 (n_48), .A1 (n_55), .B0 (n_13), .Y (n_68));
  CLKINVX1 g10806(.A (n_56), .Y (n_93));
  OAI32X1 g10808__5115(.A0 (pending_debug[0]), .A1 (hall_down_req[0]),
       .A2 (n_0), .B0 (n_31), .B1 (n_51), .Y (n_86));
  AOI21X1 g10812__7482(.A0 (n_49), .A1 (n_55), .B0 (n_9), .Y (n_75));
  NAND2XL g10799__4733(.A (n_54), .B (n_66), .Y (n_85));
  DFFRHQX1 \pending_reg[1] (.RN (rst_n), .CK (clk), .D (n_66), .Q
       (pending_debug[1]));
  NOR3X1 g10810__6161(.A (n_53), .B (n_60), .C (n_90), .Y (n_101));
  AOI31X1 g10821__9315(.A0 (n_52), .A1 (n_59), .A2 (n_57), .B0 (n_11),
       .Y (n_73));
  NOR2XL g10815__9945(.A (current_floor[2]), .B (n_51), .Y (n_67));
  AOI31X1 g10814__2883(.A0 (current_floor[1]), .A1 (n_57), .A2 (n_49),
       .B0 (n_10), .Y (n_56));
  NAND2XL g10817__2346(.A (current_floor[2]), .B (n_51), .Y (n_65));
  NOR2XL g10816__1666(.A (current_floor[2]), .B (n_55), .Y (n_76));
  AOI21X1 g10813__7410(.A0 (n_48), .A1 (n_45), .B0 (n_6), .Y (n_71));
  AOI31X1 g10801__6417(.A0 (n_83), .A1 (current_floor[0]), .A2 (n_48),
       .B0 (n_7), .Y (n_72));
  NAND2XL g10823__5477(.A (target_floor[0]), .B (n_57), .Y (n_46));
  CLKINVX1 g10824(.A (n_45), .Y (n_51));
  AOI21X1 g10820__2398(.A0 (current_floor[0]), .A1 (n_43), .B0 (n_12),
       .Y (n_66));
  NOR2XL g10825__5107(.A (n_83), .B (n_57), .Y (n_55));
  OAI211X1 g10811__6260(.A0 (emergency_stop), .A1 (n_201), .B0 (n_44),
       .C0 (n_30), .Y (n_142));
  CLKINVX1 g10818(.A (n_90), .Y (n_63));
  AOI32X1 g10822__4319(.A0 (n_24), .A1 (n_29), .A2 (n_119), .B0
       (n_119), .B1 (n_40), .Y (n_90));
  NOR2XL g10826__8428(.A (current_floor[1]), .B (current_floor[0]), .Y
       (n_45));
  OAI21X1 g10819__5526(.A0 (emergency_stop), .A1 (n_37), .B0 (n_44), .Y
       (n_62));
  CLKINVX1 g10829(.A (current_floor[0]), .Y (n_57));
  NOR2XL g10828__6783(.A (n_39), .B (n_54), .Y (n_43));
  CLKINVX1 g10839(.A (n_41), .Y (n_44));
  OAI21X1 g10832__1617(.A0 (floor_sensor[6]), .A1 (n_28), .B0 (n_21),
       .Y (current_floor[0]));
  OAI21X1 g10831__2802(.A0 (n_39), .A1 (n_38), .B0 (n_34), .Y (n_40));
  AOI21X1 g10827__1705(.A0 (n_4), .A1 (n_25), .B0 (maintenance_mode),
       .Y (n_37));
  NOR2XL g10843__5122(.A (motor_brake), .B (emergency_stop), .Y (n_41));
  NOR2XL g10833__8246(.A (target_floor[1]), .B (n_83), .Y (n_33));
  NAND2XL g10837__7098(.A (n_98), .B (n_83), .Y (n_54));
  NOR2XL g10834__6131(.A (n_98), .B (n_83), .Y (n_59));
  NAND2XL g10841__1881(.A (target_floor[2]), .B (n_98), .Y (n_32));
  INVXL g10838(.A (n_49), .Y (n_31));
  NAND2XL g10846__5115(.A (n_29), .B (n_119), .Y (n_30));
  NOR2XL g10847__7482(.A (n_39), .B (n_98), .Y (n_48));
  AOI2BB1XL g10840__4733(.A0N (floor_sensor[4]), .A1N (n_16), .B0
       (floor_sensor[5]), .Y (n_28));
  NAND3BX1 g10836__6161(.AN (n_27), .B (state[1]), .C (n_26), .Y
       (n_34));
  OAI21XL g10852__9315(.A0 (state[1]), .A1 (n_26), .B0 (n_19), .Y
       (motor_brake));
  CLKINVX1 g10844(.A (n_83), .Y (current_floor[1]));
  NOR2XL g10842__9945(.A (n_39), .B (current_floor[2]), .Y (n_49));
  OAI21X1 g10845__2883(.A0 (n_24), .A1 (door_closed_sensor), .B0
       (n_23), .Y (n_25));
  AOI211X1 g10848__2346(.A0 (n_20), .A1 (n_2), .B0 (floor_sensor[6]),
       .C0 (floor_sensor[7]), .Y (n_83));
  NOR2BX1 g10849__1666(.AN (door_close_cmd), .B (door_closed_sensor),
       .Y (n_29));
  CLKINVX1 g10855(.A (current_floor[2]), .Y (n_98));
  NAND2BX1 g10853__7410(.AN (door_close_btn), .B (n_24), .Y (n_38));
  NAND2BX1 g10854__6417(.AN (door_open_sensor), .B (n_24), .Y (n_27));
  NAND3BX1 g10861__5477(.AN (floor_sensor[6]), .B (n_21), .C (n_20), .Y
       (current_floor[2]));
  INVXL g10862(.A (door_open_cmd), .Y (n_19));
  AND2XL g10868__2398(.A (n_23), .B (n_26), .Y (motor_up));
  CLKINVX1 g10867(.A (n_39), .Y (n_52));
  AOI21X1 g10864__5107(.A0 (floor_sensor[1]), .A1 (n_1), .B0
       (floor_sensor[3]), .Y (n_16));
  NOR2XL g10865__6260(.A (state[1]), .B (n_3), .Y (door_close_cmd));
  AND2XL g10863__4319(.A (state[1]), .B (n_14), .Y (motor_down));
  NOR2XL g10866__8428(.A (n_23), .B (n_14), .Y (door_open_cmd));
  NAND3X1 g10871__5526(.A (state[2]), .B (n_8), .C (n_23), .Y (n_39));
  NOR4X1 g10856__6783(.A (pending_debug[7]), .B (hall_up_req[7]), .C
       (in_car_req[7]), .D (hall_down_req[7]), .Y (n_13));
  NOR4X1 g10851__3680(.A (pending_debug[1]), .B (hall_up_req[1]), .C
       (in_car_req[1]), .D (hall_down_req[1]), .Y (n_12));
  NOR4X1 g10850__1617(.A (pending_debug[6]), .B (hall_up_req[6]), .C
       (in_car_req[6]), .D (hall_down_req[6]), .Y (n_11));
  NOR4X1 g10857__2802(.A (pending_debug[2]), .B (hall_up_req[2]), .C
       (in_car_req[2]), .D (hall_down_req[2]), .Y (n_10));
  NOR4X1 g10858__1705(.A (pending_debug[3]), .B (hall_up_req[3]), .C
       (in_car_req[3]), .D (hall_down_req[3]), .Y (n_9));
  NOR2XL g10880__5122(.A (state[2]), .B (n_8), .Y (n_26));
  NOR4X1 g10859__8246(.A (pending_debug[5]), .B (hall_up_req[5]), .C
       (in_car_req[5]), .D (hall_down_req[5]), .Y (n_7));
  NOR4X1 g10860__7098(.A (pending_debug[4]), .B (hall_up_req[4]), .C
       (in_car_req[4]), .D (hall_down_req[4]), .Y (n_6));
  XOR2XL g10869__6131(.A (door_timer[0]), .B (door_timer[1]), .Y (n_5));
  INVXL g10872(.A (n_3), .Y (n_4));
  NAND2BX1 g10873__1881(.AN (floor_sensor[3]), .B (n_1), .Y (n_2));
  OAI21X1 g10870__5115(.A0 (door_timer[3]), .A1 (door_timer[4]), .B0
       (door_timer[5]), .Y (n_24));
  OR2XL g10874__7482(.A (hall_up_req[0]), .B (in_car_req[0]), .Y (n_0));
  NAND2XL g10875__4733(.A (state[0]), .B (state[2]), .Y (n_3));
  NOR2XL g10879__6161(.A (state[0]), .B (state[2]), .Y (n_14));
  NOR2XL g10877__9315(.A (floor_sensor[4]), .B (floor_sensor[5]), .Y
       (n_20));
  NAND2XL g10878__9945(.A (door_timer[0]), .B (door_timer[1]), .Y
       (n_60));
  NOR2XL g10876__2883(.A (maintenance_mode), .B (emergency_stop), .Y
       (n_119));
  CLKINVX1 g10882(.A (floor_sensor[2]), .Y (n_1));
  CLKINVX1 g10881(.A (floor_sensor[7]), .Y (n_21));
  DFFRX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_160), .Q
       (state[0]), .QN (n_8));
  DFFRX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (n_149), .Q
       (state[1]), .QN (n_23));
  DFFRX1 \door_timer_reg[2] (.RN (rst_n), .CK (clk), .D (n_91), .Q
       (door_timer[2]), .QN (n_53));
  NAND4BXL g2(.AN (n_75), .B (n_80), .C (n_86), .D (n_93), .Y (n_200));
  NOR2BXL g10913(.AN (n_34), .B (n_52), .Y (n_201));
endmodule

